Clears input field.
ats1999/time-stamp pull request #22
Opened 2022-01-18 09:43 UTC by bugsmithd

It clears the minutes' input field after a successful HTTP request.

#19 Fixes.

2022-01-18 09:52 UTC, anshu1992 commented
@ats1999 Please review and let me know if any changes are required, thanks!

2022-01-20 14:10 UTC, ats1999 requested changes

2022-01-20 14:10 UTC, ats1999 commented on pages/back-date.js
> +        minutesInputRef.current.value = '';
Can you check, `current.value`  should be a number or string

2022-01-20 14:10 UTC, ats1999 commented on pages/back-date.js
> +        setTime('');
Please make sure that time value can be a string

2022-01-20 14:13 UTC, anshu1992 commented on pages/back-date.js
> +        minutesInputRef.current.value = '';
@ats1999 If I set `current.value` to a number then it will show that number instead of a blank field, so used `''`.

2022-01-20 14:15 UTC, anshu1992 commented on pages/back-date.js
> +        setTime('');
@ats1999 to set the current field as empty I set the value to be the empty string. It also disables the submit button when the value is empty string enforcing the user to set any other value to submit the form.

2022-01-20 14:21 UTC, ats1999 commented on pages/back-date.js
> +        minutesInputRef.current.value = '';
Great man

2022-01-20 14:22 UTC, ats1999 commented on pages/back-date.js
> +        setTime('');
Okey, i am approving the changes. 

Thanks for contribution

2022-01-20 14:22 UTC, merged